// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwNifbU_L7_jQKhpFEpGFIZlnCviia_Zs',
    appId: '1:828705460475:web:8379836ce3d2e9176c205e',
    messagingSenderId: '828705460475',
    projectId: 'new-furniture-app-mvc',
    authDomain: 'new-furniture-app-mvc.firebaseapp.com',
    storageBucket: 'new-furniture-app-mvc.firebasestorage.app',
    measurementId: 'G-HDS3CTN8CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb6kyDdN_OIRYlnNUv068YAmRBA165bn4',
    appId: '1:828705460475:android:3b30aa9796bd66a36c205e',
    messagingSenderId: '828705460475',
    projectId: 'new-furniture-app-mvc',
    storageBucket: 'new-furniture-app-mvc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANOkRn8epbd5SZlFIYMaVWXXT3CAaa-24',
    appId: '1:828705460475:ios:880c5b7eeeb675146c205e',
    messagingSenderId: '828705460475',
    projectId: 'new-furniture-app-mvc',
    storageBucket: 'new-furniture-app-mvc.firebasestorage.app',
    iosBundleId: 'com.example.newFurinitureAppMvc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANOkRn8epbd5SZlFIYMaVWXXT3CAaa-24',
    appId: '1:828705460475:ios:880c5b7eeeb675146c205e',
    messagingSenderId: '828705460475',
    projectId: 'new-furniture-app-mvc',
    storageBucket: 'new-furniture-app-mvc.firebasestorage.app',
    iosBundleId: 'com.example.newFurinitureAppMvc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwNifbU_L7_jQKhpFEpGFIZlnCviia_Zs',
    appId: '1:828705460475:web:3f978c66d83ae3de6c205e',
    messagingSenderId: '828705460475',
    projectId: 'new-furniture-app-mvc',
    authDomain: 'new-furniture-app-mvc.firebaseapp.com',
    storageBucket: 'new-furniture-app-mvc.firebasestorage.app',
    measurementId: 'G-67DJ2WGVZR',
  );
}
